[project]
name = "black-box-capstone"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Arwel Brown", email = "arwel.brown@hotmail.co.uk" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.4.0",
    "numpy>=2.5.3",
    "scikit-learn>=1.9.1",
    "scipy>=1.18.1",
]

[project.scripts]
black-box-capstone = "black_box_capstone:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
